---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 774356142751383552-4lxUD1ZFIij7wSFL7D1RTSA6esFfjXk
:access_token_secret: kOYAkTmiMqq5HaOPU83A0o6fGLIKzGlJx8n4fLSD9Ajnx
